sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sabusingh.bhatia/docker-go .

script:
 # - docker run sabusingh.bhatia/docker-go go test . -v -test.benchmem -cover
 # - docker-compose -f docker-compose.yml up

