version:  '3.0'
services:
  tests:
    build:
      context:  .
      dockerfile: Dockerfile.dev
    image: sabusingh.bhatia/webapp_test
    command:  ["go", "test", "-v", "-cover", "-test.benchmem", "."]